window.MalAngenommenConfig = {
	categoryStyles: {
		hypothetical: {
			label: 'Hypothetical',
			className: 'theme-hypothetical',
			text: '#fff9f6',
			logoSrc: 'Media/Logos/hypothetical_logo.GIF',
			coreColor: '#e0b326',
			logoColor: '#e0b326',
			patternSrc: "Media/Patterns/Hypothetical Muster8.svg",
			patternColorA: '#f7e971',
			patternColorB: '#e0b326',
			circleFillColor: '#f7e971',
			questionShellBg: '#fff7cd',
			questionShellText: '#4a3400',
			questionShellBorder: '#b08c00',
			accent: '#ff8a5b',
			accentSoft: 'rgba(255, 138, 91, 0.18)',
			top: 'rgba(38, 23, 31, 0.96)',
			bottom: 'rgba(14, 10, 18, 0.97)'
		},
		showstopper: {
			label: 'Showstopper',
			className: 'theme-showstopper',
			text: '#f4fbff',
			logoSrc: 'Media/Logos/Showstopper_logo.GIF',
			coreColor: '#90af31',
			logoColor: '#90af31',
			patternSrc: "Media/Patterns/Showstopper Muster8.svg",
			patternColorA: '#90af31',
			patternColorB: '#c6d977',
			circleFillColor: '#c6d977',
			questionShellBg: '#f5ffd6',
			questionShellText: '#234200',
			questionShellBorder: '#6f8f19',
			accent: '#6fc4ff',
			accentSoft: 'rgba(111, 196, 255, 0.16)',
			top: 'rgba(17, 28, 44, 0.96)',
			bottom: 'rgba(10, 14, 26, 0.98)'
		},
		kombichaos: {
			label: 'Kombichaos',
			className: 'theme-kombichaos',
			text: '#f7fff1',
			logoSrc: 'Media/Logos/kombichaos_logo.GIF',
			coreColor: '#cd652e',
			logoColor: '#cd652e',
			patternSrc: "Media/Patterns/Kombichaos Muster8.svg",
			patternColorA: '#cd652e',
			patternColorB: '#dda0c4',
			circleFillColor: '#dda0c4',
			questionShellBg: '#ffd7c8',
			questionShellText: '#5a1d00',
			questionShellBorder: '#b34d1f',
			accent: '#9eff7a',
			accentSoft: 'rgba(158, 255, 122, 0.16)',
			top: 'rgba(20, 30, 18, 0.96)',
			bottom: 'rgba(10, 16, 12, 0.98)'
		},
		monkeyspaw: {
			label: 'Monkey’s Paw',
			className: 'theme-monkeyspaw',
			text: '#fff7e9',
			logoSrc: 'Media/Logos/MonkeysPaw_logo.GIF',
			coreColor: '#2f56a8',
			logoColor: '#2f56a8',
			patternSrc: "Media/Patterns/Monkey's Paw Muster8.svg",
			patternColorA: '#2f56a8',
			patternColorB: '#9d87bf',
			circleFillColor: '#9d87bf',
			questionShellBg: '#eee6ff',
			questionShellText: '#18114c',
			questionShellBorder: '#5a45a0',
			accent: '#ffc45c',
			accentSoft: 'rgba(255, 196, 92, 0.16)',
			top: 'rgba(35, 27, 17, 0.96)',
			bottom: 'rgba(15, 11, 7, 0.98)'
		},
		default: {
			label: 'Other',
			className: 'theme-default',
			text: '#111111',
			logoSrc: '',
			coreColor: '#6b6b6b',
			logoColor: '#6b6b6b',
			patternSrc: '',
			patternColorA: '#f0f0f0',
			patternColorB: '#d0d0d0',
			circleFillColor: '#d0d0d0',
			questionShellBg: '#ffffff',
			questionShellText: '#111111',
			questionShellBorder: '#e0e0e0',
			accent: '#8a8a8a',
			accentSoft: 'rgba(138, 138, 138, 0.12)',
			top: 'rgba(24,24,24,0.9)',
			bottom: 'rgba(10,10,10,0.9)'
		}
	},
	variationVisuals: [
		{ patternSrc: 'Media/Patterns/Variation Muster_18.svg', colorA: '#8b64a9', colorB: '#bda8cf' },
		{ patternSrc: 'Media/Patterns/Variation Muster_28.svg', colorA: '#d065a5', colorB: '#dda0c4' },
		{ patternSrc: 'Media/Patterns/Variation Muster_38.svg', colorA: '#a85e8d', colorB: '#b390c0' },
		{ patternSrc: 'Media/Patterns/Variation Muster_48.svg', colorA: '#cde2df', colorB: '#e3b1d0' }
	],
	avatarImageSources: [],
	answerText: {
		de: {
			toggle: 'Eigene Antwort',
			name: 'Name',
			answer: 'Antwort',
			namePlaceholder: 'Gib deinen Namen ein',
			answerPlaceholder: 'Schreib deine Antwort auf die Frage',
			submit: 'Senden',
			submitting: 'Wird gesendet...',
			cancel: 'Schliessen',
			leaderboard: 'Leaderboard',
			showLeaderboard: 'Leaderboard',
			hideLeaderboard: 'Zuruck',
			empty: 'Noch keine Antworten.',
			success: 'Antwort gesendet.',
			error: 'Antwort konnte nicht gesendet werden.',
			countSingular: '1 Antwort',
			countPlural: (count) => `${count} Antworten`
		},
		en: {
			toggle: 'Your answer',
			name: 'Name',
			answer: 'Answer',
			namePlaceholder: 'Enter your name',
			answerPlaceholder: 'Write your answer to the question',
			submit: 'Send',
			submitting: 'Sending...',
			cancel: 'Close',
			leaderboard: 'Leaderboard',
			showLeaderboard: 'Leaderboard',
			hideLeaderboard: 'Close',
			empty: 'No answers yet.',
			success: 'Answer sent.',
			error: 'Answer could not be sent.',
			countSingular: '1 answer',
			countPlural: (count) => `${count} answers`
		}
	}
}
